services:
  - type: web
    name: roadvision-app
    runtime: docker
    plan: free
    region: oregon
    branch: main
    envVars:
      - key: PORT
        value: 10000
      - key: PYTHONUNBUFFERED
        value: "1"
